/*
This file exports all the types available in the recommended API revision. Thereby, things MAY break in the future.
Try sticking to imports from a specific revision.
*/

export {
  type WKApiRevision,
  type WKAssignment,
  type WKAssignmentCollection,
  type WKAssignmentData,
  type WKAssignmentParameters,
  type WKAssignmentPayload,
  type WKAssignmentRequests,
  type WKCollection,
  type WKCollectionParameters,
  type WKCollectionParametersMap,
  type WKCreatedReview,
  type WKDatableString,
  type WKError,
  type WKKanaVocabulary,
  type WKKanaVocabularyCollection,
  type WKKanaVocabularyData,
  type WKKanji,
  type WKKanjiCollection,
  type WKKanjiData,
  type WKKanjiReading,
  type WKLessonBatchSizeNumber,
  type WKLevel,
  type WKLevelProgression,
  type WKLevelProgressionCollection,
  type WKLevelProgressionData,
  type WKLevelProgressionParameters,
  type WKLevelProgressionRequests,
  type WKMaxLessonBatchSize,
  type WKMaxLevels,
  type WKMaxSrsReviewStages,
  type WKMaxSrsStages,
  type WKMinLessonBatchSize,
  type WKMinLevels,
  type WKPayloadMap,
  type WKRadical,
  type WKRadicalCharacterImage,
  type WKRadicalCharacterImagePngMetadata,
  type WKRadicalCharacterImageSvgMetadata,
  type WKRadicalCollection,
  type WKRadicalData,
  type WKReport,
  type WKRequest,
  type WKRequestFactoryInit,
  type WKRequestGetOptions,
  type WKRequestHeaders,
  type WKRequestPostPutOptions,
  type WKReset,
  type WKResetCollection,
  type WKResetData,
  type WKResetParameters,
  type WKResetRequests,
  type WKResource,
  type WKResourceType,
  type WKReview,
  type WKReviewCollection,
  type WKReviewData,
  type WKReviewObjectWithAssignmentId,
  type WKReviewObjectWithSubjectId,
  type WKReviewParameters,
  type WKReviewPayload,
  type WKReviewRequests,
  type WKReviewStatistic,
  type WKReviewStatisticCollection,
  type WKReviewStatisticData,
  type WKReviewStatisticParameters,
  type WKReviewStatisticRequests,
  type WKSpacedRepetitionSystem,
  type WKSpacedRepetitionSystemCollection,
  type WKSpacedRepetitionSystemData,
  type WKSpacedRepetitionSystemParameters,
  type WKSpacedRepetitionSystemRequests,
  type WKSpacedRepetitionSystemStage,
  type WKSrsStageNumber,
  type WKStudyMaterial,
  type WKStudyMaterialBaseData,
  type WKStudyMaterialCollection,
  type WKStudyMaterialCreatePayload,
  type WKStudyMaterialData,
  type WKStudyMaterialParameters,
  type WKStudyMaterialRequests,
  type WKStudyMaterialUpdatePayload,
  type WKSubject,
  type WKSubjectAuxiliaryMeaning,
  type WKSubjectCollection,
  type WKSubjectData,
  type WKSubjectMeaning,
  type WKSubjectParameters,
  type WKSubjectRequests,
  type WKSubjectTuple,
  type WKSubjectType,
  type WKSummary,
  type WKSummaryData,
  type WKSummaryLesson,
  type WKSummaryRequests,
  type WKSummaryReview,
  type WKUser,
  type WKUserData,
  type WKUserPreferences,
  type WKUserPreferencesPayload,
  type WKUserRequests,
  type WKUserSubscription,
  type WKVocabulary,
  type WKVocabularyCollection,
  type WKVocabularyContextSentence,
  type WKVocabularyData,
  type WKVocabularyPronunciationAudio,
  type WKVocabularyReading,
  type WKVoiceActor,
  type WKVoiceActorCollection,
  type WKVoiceActorData,
  type WKVoiceActorParameters,
  type WKVoiceActorRequests,
  WK_API_REVISION,
  WK_MAX_LESSON_BATCH_SIZE,
  WK_MAX_LEVELS,
  WK_MAX_SRS_REVIEW_STAGES,
  WK_MAX_SRS_STAGES,
  WK_MIN_LESSON_BATCH_SIZE,
  WK_MIN_LEVELS,
  WK_SUBJECT_MARKUP_MATCHERS,
  WKRequestFactory,
  isWKDatableString,
  isWKLessonBatchSizeNumber,
  isWKLevel,
  isWKLevelArray,
  isWKSrsStageNumber,
  isWKSrsStageNumberArray,
  stringifyParameters,
  validateParameters,
  validatePayload,
} from "./v20170710.js";
