name: Tests (Main)
on: workflow_dispatch
jobs:
  test:
    name: "Rebuild and Deploy Docs"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: "curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}"
