name: Tests (Main)
on:
  release:
    types: [published]
jobs:
  test:
    name: "Publish Release"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - name: Install Latest NPM Version
        run: npm install -g npm@latest
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Run Unit Tests
        run: npm test
      - name: Build Documentation
        run: npm run build:docs
      - name: Build Library
        run: npm run build
      - name: Publish Library
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Documentation
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bachmacintosh-wanikani-api-types
          directory: "./docs"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
